server:
  port: 18080

auth:
  oauth2:
    client:
      provider:
        zitadel:
          issuer-uri: 'http://localhost:8081'
          user-name-attribute: preferred_username
      registration:
        zitadel:
          client-id: '253167323886714883@dc_cms'
          client-authentication-method: none
          authorizationGrantType: authorization_code
          redirect-uri: 'http://localhost:18080/login/oauth2'
          response-type: code
          scope: >
            openid,
            profile

logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug
